# Generated by Django 3.0.3 on 2020-02-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('pic_url', models.TextField()),
                ('sub_text', models.CharField(max_length=60)),
                ('era', models.CharField(max_length=60)),
                ('bio', models.TextField()),
            ],
        ),
    ]
