# Generated by Django 3.0.3 on 2020-02-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_people_api', '0002_auto_20200223_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
